# Generated by Django 3.2.7 on 2021-09-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210908_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='record',
            name='procedure',
        ),
        migrations.AddField(
            model_name='record',
            name='procedure',
            field=models.ManyToManyField(to='main.Procedures'),
        ),
    ]
