# Generated by Django 3.2.7 on 2021-10-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210909_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_text',
            field=models.CharField(max_length=256, null=True, unique=True, verbose_name='Опис'),
        ),
    ]
