# Generated by Django 3.2.7 on 2021-10-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_text',
            field=models.CharField(max_length=256, null=True, verbose_name='Опис'),
        ),
    ]
